// lib/syslog/eventStore.js
//
// Persistence for syslog events: daily partition management, batched inserts,
// and the rollups. CommonJS — services/collector.js loads it under plain node.
//
// The SQL-BUILDING half is pure and unit-tested (tests/eventStore.test.js);
// the pool-touching half is a thin wrapper over it. That split exists because
// the parameter-limit arithmetic and the partition boundary maths are exactly
// the kind of thing that is silently wrong at 3am under load.
//
// ⛔ pool is always a PARAMETER, never module-global (CLAUDE.md).
// ⛔ Parameterized queries only. Identifiers (partition names) are the one
//    thing that cannot be parameterized, so they are built from a Date and
//    validated against a strict pattern before ever reaching the server.

'use strict';

// PostgreSQL's wire protocol caps a statement at 65535 bytes' worth of
// parameters. 27 columns x 500 rows = 13,500 -- comfortably inside it, while
// still being few enough statements to keep up with ~1,100 events/sec.
const COLUMNS = [
  'received_at', 'event_at', 'tz_assumed', 'source_ip', 'device_id', 'vendor',
  'facility', 'severity', 'hostname', 'program', 'action', 'src_ip', 'dst_ip',
  'src_port', 'dst_port', 'protocol', 'application', 'src_zone', 'dst_zone',
  'rule_id', 'rule_uuid', 'rule_name', 'bytes_sent', 'bytes_received', 'log_class', 'bytes_summable', 'message',
];
const MAX_ROWS_PER_INSERT = 500;

// A partition name is an IDENTIFIER and therefore cannot be a bind parameter.
// It is always generated by partitionNameFor() below, but this pattern is
// asserted before interpolation anyway -- an identifier built from anything
// user-influenced is how SQL injection gets into an otherwise parameterized
// codebase.
const SAFE_PARTITION_RE = /^syslog_events_\d{8}$/;

function pad(n) { return String(n).padStart(2, '0'); }

/** UTC day key, e.g. Date -> '20260908'. Partitions are UTC so they do not
 *  shift under DST and so a boundary is the same instant everywhere. */
function dayKey(date) {
  return `${date.getUTCFullYear()}${pad(date.getUTCMonth() + 1)}${pad(date.getUTCDate())}`;
}

function partitionNameFor(date) {
  return `syslog_events_${dayKey(date)}`;
}

/** ISO date (UTC midnight) for a partition bound. */
function boundFor(date) {
  return `${date.getUTCFullYear()}-${pad(date.getUTCMonth() + 1)}-${pad(date.getUTCDate())}`;
}

function addDaysUtc(date, days) {
  const d = new Date(date.getTime());
  d.setUTCDate(d.getUTCDate() + days);
  d.setUTCHours(0, 0, 0, 0);
  return d;
}

/**
 * DDL for one day's partition. IF NOT EXISTS so it is safe to run every cycle.
 * @returns {{name: string, sql: string}}
 */
function buildPartitionSql(date) {
  const name = partitionNameFor(date);
  if (!SAFE_PARTITION_RE.test(name)) {
    throw new Error(`refusing to build DDL for unsafe partition name: ${name}`);
  }
  const from = boundFor(date);
  const to = boundFor(addDaysUtc(date, 1));
  return {
    name,
    sql:
      `CREATE TABLE IF NOT EXISTS ${name} PARTITION OF syslog_events ` +
      `FOR VALUES FROM ('${from}') TO ('${to}')`,
  };
}

/** Multi-row parameterized INSERT for `rowCount` rows. */
function buildInsertSql(rowCount) {
  if (!Number.isInteger(rowCount) || rowCount < 1) {
    throw new Error(`buildInsertSql needs a positive row count, got ${rowCount}`);
  }
  const tuples = [];
  let p = 1;
  for (let r = 0; r < rowCount; r++) {
    const slots = [];
    for (let c = 0; c < COLUMNS.length; c++) slots.push(`$${p++}`);
    tuples.push(`(${slots.join(',')})`);
  }
  return `INSERT INTO syslog_events (${COLUMNS.join(',')}) VALUES ${tuples.join(',')}`;
}

// --- value coercion --------------------------------------------------------
// ⛔ Every one of these returns null rather than a substitute value. An INET
// column will reject a malformed address and abort the whole batch, so a
// firewall that logs a hostname where an IP belongs must yield NULL, not a
// dropped batch and not 0.0.0.0.

const IPV4_RE = /^\d{1,3}(\.\d{1,3}){3}$/;
const IPV6_RE = /^[0-9a-fA-F:]+$/;

function toInetOrNull(v) {
  if (typeof v !== 'string' || v.length === 0) return null;
  const s = v.trim();
  if (IPV4_RE.test(s)) {
    return s.split('.').every((o) => Number(o) <= 255) ? s : null;
  }
  if (s.includes(':') && IPV6_RE.test(s)) return s;
  return null;
}

function toIntOrNull(v) {
  if (v === null || v === undefined || v === '') return null;
  const n = Number(v);
  return Number.isFinite(n) ? Math.trunc(n) : null;
}

function toPortOrNull(v) {
  const n = toIntOrNull(v);
  // A port outside 0-65535 is a mis-parse, not a port.
  return n === null || n < 0 || n > 65535 ? null : n;
}

function toTextOrNull(v, max) {
  if (v === null || v === undefined) return null;
  const s = String(v);
  if (s.length === 0) return null;
  return max && s.length > max ? s.slice(0, max) : s;
}

/**
 * Flatten a collector event into the bind parameters for one row, in COLUMNS
 * order. Never throws — a row that cannot be coerced still stores its raw
 * message, which is the one field that must never be lost.
 */
function flattenRow(e) {
  return [
    e.receivedAt,
    e.eventAt || null,
    e.tzAssumed === true,
    toInetOrNull(e.sourceIp),
    e.deviceId || null,
    toTextOrNull(e.vendor, 32),
    toIntOrNull(e.facility),
    toIntOrNull(e.severity),
    toTextOrNull(e.hostname, 255),
    toTextOrNull(e.program, 128),
    toTextOrNull(e.action, 64),
    toInetOrNull(e.srcIp),
    toInetOrNull(e.dstIp),
    toPortOrNull(e.srcPort),
    toPortOrNull(e.dstPort),
    toTextOrNull(e.protocol, 32),
    toTextOrNull(e.application, 128),
    toTextOrNull(e.srcZone, 128),
    toTextOrNull(e.dstZone, 128),
    toTextOrNull(e.ruleId, 64),
    toTextOrNull(e.ruleUuid, 64),
    toTextOrNull(e.ruleName, 255),
    toIntOrNull(e.bytesSent),
    toIntOrNull(e.bytesReceived),
    toTextOrNull(e.logClass, 32),
    e.bytesSummable === true,
    // message is NOT NULL in the schema; an empty raw line still gets ''.
    e.message === null || e.message === undefined ? '' : String(e.message),
  ];
}

function chunk(arr, size) {
  const out = [];
  for (let i = 0; i < arr.length; i += size) out.push(arr.slice(i, i + size));
  return out;
}

// --- DB operations ---------------------------------------------------------

/**
 * Create today's, tomorrow's and (defensively) yesterday's partitions.
 * Yesterday matters because an event can arrive with a received_at just before
 * a UTC midnight rollover; without the partition the INSERT fails outright.
 */
async function ensurePartitions(pool, now) {
  const base = now instanceof Date ? now : new Date();
  const made = [];
  for (const offset of [-1, 0, 1]) {
    const { name, sql } = buildPartitionSql(addDaysUtc(base, offset));
    await pool.query(sql);
    made.push(name);
  }
  return made;
}

/**
 * Drop partitions older than `retentionDays`.
 * ⛔ DROP the partition; never DELETE the rows. At ~93M rows/day a DELETE would
 * cost more WAL and vacuum than the ingest itself and would not return space.
 */
async function dropOldPartitions(pool, retentionDays, now) {
  const days = Number.isFinite(Number(retentionDays)) && Number(retentionDays) >= 1
    ? Math.trunc(Number(retentionDays))
    : 7;
  const base = now instanceof Date ? now : new Date();
  const cutoff = addDaysUtc(base, -days);
  const { rows } = await pool.query(
    `SELECT c.relname AS name
       FROM pg_class c
       JOIN pg_inherits i ON i.inhrelid = c.oid
       JOIN pg_class p ON p.oid = i.inhparent
      WHERE p.relname = 'syslog_events'`
  );
  const dropped = [];
  for (const r of rows) {
    if (!SAFE_PARTITION_RE.test(r.name)) continue; // never touch anything unexpected
    const key = r.name.slice('syslog_events_'.length);
    if (key < dayKey(cutoff)) {
      await pool.query(`DROP TABLE IF EXISTS ${r.name}`);
      dropped.push(r.name);
    }
  }
  return dropped;
}

/**
 * Insert a batch of events, chunked to stay inside the bind-parameter limit.
 * @returns {{stored: number, failedChunks: number}}
 */
async function insertEvents(pool, events) {
  if (!Array.isArray(events) || events.length === 0) return { stored: 0, failedChunks: 0 };
  let stored = 0;
  let failedChunks = 0;
  for (const group of chunk(events, MAX_ROWS_PER_INSERT)) {
    const sql = buildInsertSql(group.length);
    const params = [];
    for (const e of group) params.push(...flattenRow(e));
    try {
      await pool.query(sql, params);
      stored += group.length;
    } catch (err) {
      // One bad chunk must not sink the rest of the flush. The spool file is
      // only removed by the caller once it knows how much landed, so nothing
      // is silently discarded.
      failedChunks += 1;
      // eslint-disable-next-line no-console
      console.warn(`[collector] insert chunk of ${group.length} failed: ${err.message}`);
    }
  }
  return { stored, failedChunks };
}

module.exports = {
  COLUMNS,
  MAX_ROWS_PER_INSERT,
  partitionNameFor,
  buildPartitionSql,
  buildInsertSql,
  flattenRow,
  chunk,
  toInetOrNull,
  toPortOrNull,
  toIntOrNull,
  toTextOrNull,
  ensurePartitions,
  dropOldPartitions,
  insertEvents,
};
